/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import { getWeatherAsync } from './thunks';
import { WeatherSliceState } from '@/lib/redux/typings';

const initialState: WeatherSliceState = {
  icon: undefined,
  main: null,
  description: null,
  status: 'idle',
  name: null,
  lat: 0,
  lon: 0
}

export const weatherSlice = createSlice({
  name: 'weather',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getWeatherAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getWeatherAsync.fulfilled, (state, action: PayloadAction<WeatherSliceState>) => {
        state.status = 'idle'
        state.main = action.payload.main
        state.description = action.payload.description
        state.icon = action.payload.icon
        state.name = action.payload.name
        state.lat = action.payload.lat
        state.lon = action.payload.lon
      })
  },
})